name = input("please enter your name")
print("your name is ", name)
age = int(input("please enter your age"))
print("your age is ", age)
Yearold = int((2020 - age) + 100)
print('year when your are 100 is', Yearold)
